### PR TITLE
Grails 3 migration changes

### PR DESCRIPTION
**Pull request by brandonlenz**
For now this is just a PR for us to conveniently track the commits and diffs for the grails 3 migration effort

### CODE REVIEW

**Comment by brandonlenz** [comment]
@ableonard @itsMicah @tommymcn 

Added you guys here just so everyone is aware there was a small change to the grails-3 version of Mandrill to make it compatible as a dependency of Grails 3.1.x apps. This will be important when trying to set up the NS pipeline like we talked about this morning.

(https://expapp.atlassian.net/wiki/spaces/ENG/pages/995393541/Upgrade+gotchas#Building-a-Grails-3.2.x+-dependency-under-a-Grails-3.1.x-app/plugin)

**Comment by dvaughn555** [comment]
Brandon - Please remove me from this list.  Thanks

**Comment by tommymcn** [comment]
@dvaughn555 this is actually a public repo and we can not remove watchers from it. You will need to go to this repo and "unwatch" it.

**Comment by arosenb2** [comment]
So glad to see that Grails 3 is finally happening! I know it’s been a long time coming!

@tommymcn @ableonard I hope y’all are doing well!

**Pull request closed without merging**
